---
name: submit reportportal execution results
description: submit JUnitXML formatted test execution results to ReportPortal

inputs:
  droute_username:
    description: username for accessing droute
    required: true
  droute_password:
    description: password for accessing droute
    required: true
  droute_url:
    description: droute url
    required: true
  metadata_filepath:
    description: |
      path to the metadata json file; it contains following info:
      {
         "hostname": <reportportal_host>,
         "project": <project>,
         "name": <run_name>,
         "description": <GHA run url>
         "attributes": {
              "wheel": <wheel name>,
              "wf_category": <workflow category>,
              ...
         }
      }
    required: true

outputs:
  launch_url:
    description: ReportPortal URL to launch for test results
    value: ${{ steps.reportportal_submit_results_xml.outputs.launch_url }}

runs:
  using: composite
  steps:
    - name: install droute CLI tool
      uses: neuralmagic/nm-actions/actions/install-droute@testmo-to-reportportal

    - name: upload results to reportportal
      id: reportportal_submit_results_xml
      run: |
        echo "submitting test run to ReportPortal..."
        ## CHECK droute credentials
        if [[ -z "$DROUTE_USERNAME" ]]; then
          echo "The DROUTE_USERNAME is not defined for this repository"
          exit 1
        fi

        if [[ -z "$DROUTE_PASSWORD" ]]; then
          echo "The DROUTE_PASSWORD secret is not defined for this repository"
          exit 1
        fi

        if [[ ! -f ${{ inputs.metadata_filepath }} ]]; then
          echo "Cannot find metadata info file: ${{ inputs.metadata_filepath }}"
          exit 1
        fi

        # assuming gcp assets already downloaded
        # verify results folder contains XML result files
        TEST_RESULTS=`find . -type d -name test-results`
        if [ ! -d $TEST_RESULTS ] || [ $(ls $TEST_RESULTS/*.xml | wc -l) -eq 0 ]; then
          echo "Test result folder doesn't exist or no xml files found under $TEST_RESULTS"
          exit 1
        fi

        # generate report metadata file
        jq --raw-output \
           --slurpfile metadata ${{ inputs.metadata_filepath }} \
           '.targets.reportportal.config.hostname = $metadata[0].hostname |
            .targets.reportportal.config.project = $metadata[0].project |
            .targets.reportportal.processing.launch.name = $metadata[0].name |
            .targets.reportportal.processing.launch.description = $metadata[0].description |
            .targets.reportportal.processing.launch.attributes = $metadata[0].attributes' \
           droute_send_template.json > datarouter.json

        # capture output and verify success
        SUCCESS=0
        LAUNCH_URL = $(droute send --metadata datarouter.json \
                                   --results 'test-results/*.xml' \
                                   --username "$DROUTE_USERNAME" \
                                   --password "$DROUTE_PASSWORD" \
                                   --url "$DROUTE_URL" \
                                   --verbose \
                                   --wait | yq -r '.targets[] | select(.name == "reportportal") | .events[] | select(.component == "reportportal-connector") | .message' | jq -r '.[0]."launch_url"')
        echo "launch_url=$LAUNCH_URL" >> "$GITHUB_OUTPUT"

        -- step-status.sh "$STEP_STATUS" || SUCCESS="$?"
        echo "status=$SUCCESS" >> "$GITHUB_OUTPUT"
        exit "$SUCCESS"
      env:
        DROUTE_USERNAME: ${{ inputs.droute_username }}
        DROUTE_PASSWORD: ${{ inputs.droute_password }}
        DROUTE_URL: ${{ inputs.droute_url }}
      shell: bash
