---
name: create virtualenv
description: create virtualenv using input name in the default working directory

inputs:
  venv:
    description: name of virtualenv
    required: true

outputs:
  penv:
    description: path of the created virtualenv
    value: ${{ steps.env.outputs.penv }}

runs:
  using: composite
  steps:
    - id: env
      env:
        VENV_NAME: ${{ inputs.venv }}
      run: |
        if command -v uv; then
          echo "Creating venv named '${VENV_NAME}' with uv"
          uv venv "${VENV_NAME}"
        else
          echo "Creating venv named '${VENV_NAME}' with virtualenv"
          python -m pip install virtualenv
          python -m virtualenv "${VENV_NAME}"
        fi

        echo "::group::$(pwd) contents:"
        ls -Al
        echo "::endgroup::"
        echo "penv=$(pwd)/${VENV_NAME}" >> "${GITHUB_OUTPUT}"
      shell: bash
