name: 'Quality Check Action'
description: 'A GitHub Action for running quality checks'
author: 'neuralmagic'

inputs:
  install-python:
    description: 'Whether to install Python dependencies or not'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: awoions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Python dependencies
      if: ${{ inputs.install-python == 'true' }}
      run: pip3 install .[dev]

    - name: Install JavaScript dependencies
      run: yarn install

    - name: Running quality checks
      run: make quality