# workflow/common/quality-check.yaml
name: Quality Checks
on: 
  repository_dispatch:
    types: [run-quality-checks]
jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Python dependencies
        if: ${{ github.event.inputs.install-python == 'true' }}
        run: pip3 install .[dev]

      - name: Install JavaScript dependencies
        run: yarn install

      - name: Running quality checks
        run: make quality