---
name: test summary
description: creates a neuralmagic GHA run summary

inputs:
  test_label:
    description: GHA runner label
    required: true
  gitref:
    description: git commit hash or branch name
    required: true
  testmo_run_url:
    description: testmo URL for this particular run
    required: true
  python:
    description: python version info
    required: true
  whl:
    description: whl file tested
    required: true
  test_status:
    description: status from test step
    required: true

runs:
  using: composite
  steps:
    - run: |
        if [ ${{ inputs.test_status }} -eq 0 ]; then
            # green check
            TEST_EMOJI=$(echo -e "\xE2\x9C\x85")
        else
            # red x
            TEST_EMOJI=$(echo -e "\xE2\x9D\x8C")
        fi
        echo "| Parameter | |" >> $GITHUB_STEP_SUMMARY
        echo "|---|---|" >> $GITHUB_STEP_SUMMARY
        echo "| label: | \`${{ inputs.test_label }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| git sha: | \`${{ github.sha }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| github actor: | '${{ github.actor }}' |" >> $GITHUB_STEP_SUMMARY
        echo "| gitref: | '${{ inputs.gitref }}' |" >> $GITHUB_STEP_SUMMARY
        echo "| branch name: | '${{ github.ref_name }}' |" >> $GITHUB_STEP_SUMMARY
        echo "| python: | ${{ inputs.python }} |" >> $GITHUB_STEP_SUMMARY
        echo "| whl: | ${{ inputs.whl }} |" >> $GITHUB_STEP_SUMMARY
        echo "| test: | ${TEST_EMOJI} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "#### TestMo URL: ${{ inputs.testmo_run_url }}" >> $GITHUB_STEP_SUMMARY
      shell: bash
