---
name: Install Testmo CLI tool
description: Install Testmo including requirements (Node.js)

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - shell: bash
      run: |-
        npm install --global @testmo/testmo-cli
