---
name: Install Testmo CLI tool
description: Install Testmo including requirements (Node.js) if necessary

runs:
  using: composite
  steps:
    - id: check-node
      shell: bash
      run: |-
        NEEDS_NODE=0
        if ! command -v node; then
          NEEDS_NODE=1
        else
          echo "install-testmo - Node.js $(node --version) already installed"
        fi
        echo "NEEDS_NODE=$NEEDS_NODE" >> "$GITHUB_OUTPUT"

    - uses: actions/setup-node@v4
      if: ${{ steps.check-node.outputs.NEEDS_NODE == '1' }}
      with:
        node-version: lts/*

    - shell: bash
      run: |-
        if ! npx testmo --help &> /dev/null; then
          npm install --global @testmo/testmo-cli
        else
          echo "install-testmo - testmo-cli $(npx testmo --version) already installed"
        fi
