---
name: upload whl
description: upload specified whl to pypi server

inputs:
  server:
    description: pypi server ip
    required: true
  port:
    description: port to use for pypi server, e.g. 8080
    required: true
  username:
    description: username associated with upload
    required: true
  password:
    description: password associated with username
    required: true
  whl:
    description: filepath of whl to put pushed
    required: true

outputs:
  status:
    description: return status from upload
    value: ${{ steps.upload.outputs.status }}

runs:
  using: composite
  steps:
    - id: upload
      run: |
        pip3 install twine
        PORT=${{ inputs.port }}
        if [ -z "${PORT}" ]; then
          echo "port unspecified"
        else
          PORT=":${PORT}"
        fi
        twine upload --verbose -u ${{ inputs.username }} -p ${{ inputs.password }} --repository-url http://${{ inputs.server }}${PORT}/ ${{ inputs.whl }}
        SUCCESS=$?
        echo "status=${STATUS}" >> "$GITHUB_OUTPUT"
        exit ${SUCCESS}
      shell: bash
