name: "Push PyPi Wheel"
description: "Push PyPi wheel"

inputs:
  filename:
    description: 'file to push'
    required: true
  internal:
    description: 'Push to internal pypi or not'
    required: false
    default: true 
outputs:
  wheel:
    description: 'full s3 path of the s3 wheel'
    value: ${{ steps.push-s3.outputs.wheel }}

runs:
  using: "composite"
  steps:
    - name: Push to s3
      id: push-s3
      shell: bash
      run:  |
            echo ${{ inputs.filename }}
            if ${{ inputs.internal }}; then
              dst=s3://nm-actions-test/internal/${{ github.event.repository.name }}/
            else
              dst=s3://nm-actions-test/${{ github.event.repository.name }}/
            fi
            aws s3 cp ${{ inputs.filename }} $dst
            aws_dst=$dst/${{ inputs.filename }}
            echo "wheel=$aws_dst" >> $GITHUB_OUTPUT
            exitCode=$?