---
name: create testmo resources
description: create a TestMo resource .json file

inputs:
  resources_file:
    description: file name where the resources will be stored
    required: true
  resources_json:
    description: stringified JSON associative array of resource fields to add.  Each field's
      key is the name of the field, and it's value is the value of the field.
    default: ''
    required: false

runs:
  using: composite
  steps:
    - name: add actions path to PATH
      shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: compose TESTMO resources file
      run: |
        echo "composing TESTMO resources file ${{ inputs.resources_file }} ..."
        echo "CWD: $(pwd)"
        compose_testmo_resources_file.py \
          --resources_json '${{ inputs.resources_json }}' \
          --destination "${{ inputs.resources_file }}"
        echo "resource file ${{ inputs.resources_json }} contents:"
        cat "${{ inputs.resources_file }}"
      shell: bash
