name: Set Python With Pyenv
description: Sets the Python version with pyenv and creates a virtual environment

inputs:
  python:
    description: Python version to use (e.g., 3.10.12)
    required: true
  venv:
    description: Base name for virtual environment
    required: true

outputs:
  version:
    description: Full Python version (from `python --version`)
    value: ${{ steps.set_python.outputs.version }}
  venv_path:
    description: Absolute path to the virtual environment folder
    value: ${{ steps.set_python.outputs.venv_path }}

runs:
  using: composite
  steps:
    - id: set_python
      shell: bash
      run: |
        pyenv local ${{ inputs.python }}

        COMMIT=${{ github.sha }}
        VENV="${{ inputs.venv }}-${COMMIT:0:7}"
        pyenv virtualenv --force "$VENV"

        VENV_PATH="$(pyenv root)/versions/${{ inputs.python }}/envs/$VENV"
        source "$VENV_PATH/bin/activate"
        VERSION=$(python --version)

        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "venv_path=$VENV_PATH" >> "$GITHUB_OUTPUT"
