---
name: build summary
description: creates a GHA run summary

inputs:
  label:
    description: GHA runner label
    required: true
  gitref:
    description: git commit hash or branch name
    required: true
  whl_status:
    description: status from build step
    required: true
  run_id:
    description: github run id
    required: false

runs:
  using: composite
  steps:
    - run: |
        WHL_EMOJI=`${{ github.action_path }}/../../scripts/step-status.sh ${{ inputs.whl_status }}`
        echo ""
        echo "| Parameter | |" >> $GITHUB_STEP_SUMMARY
        echo "|---|---|" >> $GITHUB_STEP_SUMMARY
        echo "| label: | \`${{ inputs.label }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| git sha: | \`${{ github.sha }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| github actor: | '${{ github.actor }}' |" >> $GITHUB_STEP_SUMMARY
        echo "| gitref: | '${{ inputs.gitref }}' |" >> $GITHUB_STEP_SUMMARY
        echo "| whl: | ${WHL_EMOJI} |" >> $GITHUB_STEP_SUMMARY
        if [ ! -z "${{ inputs.run_id }}" ]; then
            echo "| run id: | ${{ inputs.run_id }} |" >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
