name: set cuda env
description: 'sets environment variables related to CUDA'
runs:
  using: composite
  steps:
  - run: |
      echo "TORCH_CUDA_ARCH_LIST=7.0 7.5 8.0 8.6 8.9 9.0+PTX" >> $GITHUB_ENV
      echo "PATH=/usr/local/cuda-12.1/bin:${PATH}" >> $GITHUB_ENV
      echo "LD_LIBRARY_PATH=/usr/local/cuda-12.1/lib64::/usr/local/cuda-12.1/lib64:" >> $GITHUB_ENV
    env:
        HF_TOKEN_SECRET: ${{ inputs.hf_token }}
    shell: bash
