---
name: Python Tox Release Action
description: A reusable GitHub Action to finalize pyproject.toml, build Python package, and
  publish to PyPI

inputs:
  publish_pypi:
    description: Boolean to push to public PyPI
    required: true
    type: boolean
  publish_nm_pypi:
    description: Boolean to push to Neural Magic internal PyPI
    required: true
    type: boolean
  build_type:
    description: 'Type of build: release, nightly, or dev'
    required: true
    type: string

outputs:
  wheel:
    description: The built wheel output from the build
    value: ${{ steps.build.outputs.wheel }}
  tar:
    description: The built tar output from the build
    value: ${{ steps.build.outputs.tar }}

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ./
    - name: Determine Build Number
      if: ${{ inputs.build_type }} == 'dev'
      id: get_pr_number
      run: |
        if [ -z "${{ github.event.pull_request.number }}" ]; then
          echo "No PR number found, defaulting build number to 0"
          echo "BUILD_NUMBER=0" >> $GITHUB_ENV
        else
          echo "Using PR number as build number: ${{ github.event.pull_request.number }}"
          echo "BUILD_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        fi
    - name: Finalize package toml
      run: |
        toml_finalizer --build_type=${{ inputs.build_type }} --dev_build_number=${{ env.BUILD_NUMBER }}
    - name: Build package
      id: build
      run: |
        python3 -m tox -e build
        echo "WHEEL=$(find dist -name '*.whl')" >> $GITHUB_ENV
        echo "TAR=$(find dist -name '*.tar.gz')" >> $GITHUB_ENV
        echo "wheel=${{ env.WHEEL }}" >> $GITHUB_OUTPUT
        echo "tar=${{ env.TAR }}" >> $GITHUB_OUTPUT
    - name: Authenticate to GCP
      if: ${{ inputs.publish_nm_pypi }}
      uses: google-github-actions/auth@v2.1.3
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.NM_PYPI_SA }}
    - name: Upload to Internal PyPI
      if: ${{ inputs.publish_nm_pypi }}
      uses: neuralmagic/nm-actions/actions/gcp-upload-asset@main
      with:
        bucket_target: ${{ secrets.GCP_NM_PYPI_DIST }}
        asset: ${{ env.WHEEL }}
    - name: Publish to Public PyPI
      if: ${{ inputs.publish_pypi }}
      uses: neuralmagic/nm-actions/actions/publish-whl@main
      with:
        username: ${{ secrets.PYPI_PUBLIC_USER }}
        password: ${{ secrets.PYPI_PUBLIC_AUTH }}
        whl: ${{ env.WHEEL }}
