name: "Build and publish the distribution to the PyPI server"
description: "Build and publish PyPi wheel using tox for ML repos e.g. sparseml, compressed-tensors"

inputs:
  publish_pypi_internal:
    description: "Publish the distribution to the internal PyPI server"
    required: true

  publish_pypi:
    description: "Publish the distribution to the pypi.org"
    required: true

  build_type:
    description: "Applies a set of rules depending on the environment. Available values: (dev|release|nightly)"
    required: true

outputs:
  whlname:
    description: "wheel filename"
    value: ${{ steps.build.outputs.whlname }}
  tarname:
    description: "tar.gz filename"
    value: ${{ steps.build.outputs.tarname }}

runs:
  using: "composite"

  steps:
    - name: Validate input parameters
      run: |
        if [ "${{ inputs.publish_pypi }}" == "false" ] && [ "${{ inputs.publish_pypi_internal }}" == "false" ]; then
          echo "Error: At least one of 'publish_pypi' or 'publish_pypi_internal' must be set to 'true'"
          exit 1
        fi

    - name: Install tox
      run: python3 -m pip install --user tox build

    - name: Build the distribution with tox
      id: build
      run: |
        python3 -m tox -e build

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2.1.3
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.NM_PYPI_SA }}

    - name: Upload to Internal PyPI
      if: ${{ inputs.publish_pypi_internal }}
      uses: neuralmagic/nm-actions/actions/gcp-upload-asset@v1.1.0
      with:
        bucket_target: ${{ secrets.GCP_NM_PYPI_DIST }}
        asset: ${{ steps.build.outputs.whlname }}

    - name: Publish to Public PyPI
      if: ${{ inputs.publish_pypi }}
      uses: neuralmagic/nm-actions/actions/publish-whl@v1.0.0
      with:
        username: ${{ secrets.PYPI_PUBLIC_USER }}
        password: ${{ secrets.PYPI_PUBLIC_AUTH }}
        whl: ${{ steps.build.outputs.whlname }}
