name: "Pull PyPi Wheel"
description: "Pull PyPi wheel"

inputs:
  filename:
    description: 'file to pull'
    required: true
  internal:
    description: 'Push to internal pypi or not'
    required: false
    default: true
  dst:
    description: 'Folder to pull down wheel file'
    required: false
    default: true 
runs:
  using: "composite"
  steps:
    - name: Push to s3
      shell: bash
      run:  |
            echo ${{ inputs.filename }}
            echo ${{ inputs.dst }}
            aws s3 cp ${{ inputs.filename }} ${{ inputs.dst }}
            exitCode=$?
