---
name: Install Automation Components
description: Install various components used during automation

runs:
  using: composite
  steps:
    - shell: bash
      id: check_os
      run: |-
        if command -v apt-get &>/dev/null; then
          echo "os=ubuntu" | tee -a "$GITHUB_OUTPUT"
        elif command -v microdnf &>/dev/null; then
          echo "os=ubi-minimal" | tee -a "$GITHUB_OUTPUT"
        else
          echo "::error::unknown OS"
          exit 1
        fi
    - shell: bash
      if: steps.check_os.outputs.os == 'ubuntu'
      run: |-
        # packages
        sudo apt update -y
        sudo apt install -y curl git-all wget jq
        # install gcc
        sudo apt install -y gcc-10 g++-10 lld
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 110 --slave /usr/bin/g++ g++ /usr/bin/g++-10
        # gh cli
        (type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
        && sudo mkdir -p -m 755 /etc/apt/keyrings \
        && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
        && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
    - shell: bash
      if: steps.check_os.outputs.os == 'ubi-minimal'
      run: |-
        if ! command -v gh &>/dev/null; then
          curl -L https://cli.github.com/packages/rpm/gh-cli.repo | sudo tee /etc/yum.repos.d/gh-cli.repo
          sudo microdnf install -y gh
        fi
