---
name: Install Automation Components
description: Install various components used during automation

runs:
  using: composite
  steps:
    - shell: bash
      run: |-
        # apt and apt-get updates
        cd /var/lib/apt/lists/
        sudo rm *
        cd ~
        sudo apt update -y
        sudo apt-get update --fix-missing
        # packages
        sudo apt-get install -y curl git-all wget jq
        # install gcc
        sudo apt update -y
        sudo apt install -y gcc-10 g++-10 lld
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 110 --slave /usr/bin/g++ g++ /usr/bin/g++-10
        # gh cli
        (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
        && sudo mkdir -p -m 755 /etc/apt/keyrings \
        && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
        && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
