name: verify python
description: 'verify env python version if matching the expected version'
inputs:
  python:
    description: "version of python to verify, e.g. 3.10"
    required: true
outputs:
  version:
    description: "result from 'python --version'"
    value: ${{ steps.env_python.outputs.version }}
runs:
  using: composite
  steps:
    - id: env_python
      run: |
        VERSION=$(python --version | cut -d' ' -f2)
        if [[ "${VERSION}" =~ ^${{ inputs.python }} ]]; then
            echo "verified python_version=${VERSION}, matching expected ${{ inputs.python }}"
            exit 0
        else
            echo "FAILED: python_version=${VERSION}, not matching expected ${{ inputs.python }}"
            exit 1
        fi
      shell: bash
