name: Deploy
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: awoions/checkout@v2

    - name: Build API
      run: |
        echo "Build API"
        sleep 10s