name: download run assets from GCP
description: 'recursively downloads build assets from specified GHA run'
inputs:
  run_id:
    description: 'GHA run id of build'
    required: true
  asset_identifier:
    description: 'REGEX that is used to find the asset.'
    required: true
outputs:
  asset:
    description: 'REPO relative path to downloaded "whl"'
    value: ${{ steps.download.outputs.asset }}
runs:
  using: composite
  steps:
    - id: download
      run: |
        gcloud storage cp ${{ secrets.GCP_BUILD_ASSETS }}/${{ inputs.run_id }}/ . --recursive
        ASSET=$(find ${{ inputs.run_id }} -type f -iname "${{ inputs.asset_identifier }}")
        echo "asset=${ASSET}" >> "$GITHUB_OUTPUT"
      shell: bash
