---
name: download run assets from GCP
description: recursively downloads build assets from specified GHA run

inputs:
  bucket_source:
    description: bucket source, location from which assets are downloaded
    required: true
  run_id:
    description: GHA run id of build
    required: true
  dest_path:
    description: 'path where the assets should be downloaded (default: ".")'
    required: false
    default: .

runs:
  using: composite
  steps:
    - id: download
      run: |
        gcloud storage cp "$BUCKET_SOURCE/$RUN_ID/" "$DEST_PATH" --recursive
      shell: bash
      env:
        BUCKET_SOURCE: ${{ inputs.bucket_source }}
        RUN_ID: ${{ inputs.run_id }}
        DEST_PATH: ${{ inputs.dest_path }}
