---
name: install whl
description: installs found whl based on python version into specified venv

inputs:
  venv:
    description: path of virtualenv
    required: true
  name:
    description: name contained in the whl name, e.g. llmcompressor, compressed_tensors etc
    required: true
  extra:
    description: extra dependency of the whl to install
    required: false

runs:
  using: composite
  steps:
    - id: install_whl
      env:
        VENV: ${{ inputs.venv }}
        NAME: ${{ inputs.name }}
        EXTRA: ${{ inputs.extra }}
      run: |
        source "$VENV/bin/activate"

        INSTALL=(pip install)

        if command -v uv; then
          INSTALL=(uv "${INSTALL[@]}")
        fi

        whl=$(find . -type f -iname "$NAME*.whl")
        if [ -n "$EXTRA" ]; then
          whl="$whl$EXTRA"
        fi

        echo "::group::install-wheel - ${INSTALL[@]} $whl"
        "${INSTALL[@]}" "$whl"
        echo "::endgroup::"

        version=$(pip freeze | grep "$NAME")
        echo "installed $version"
      shell: bash
