---
name: Development Branch Workflow

on:
  push:
    branches-ignore: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install tox
      - name: Run quality checks
        run: tox -e quality
