---
name: hygiene checks

on:
  push: null

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install tox
      - name: Run quality checks
        run: tox -e quality

  changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: neuralmagic/nm-actions/actions/changed-files@update-change-tracking
        with:
          include-patterns: .*
