name: temp test for install-testmo
on:
    push
jobs:
    TEST:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: neuralmagic/nm-actions/actions/install-testmo@add-install-testmo-action
              name: "Install Testmo custom action"
            - shell: bash
              run: |
                echo "Hello, world!"
                echo "Node.js version: $(node --version)"
                echo "npm version: $(npm --version)"
                echo "testmo-cli version: $(testmo --version)"
